let str

// console.log('ahb acb aeb aeeb adcb axeb'.match(/a.b/g))
// console.log('aba aca aea abba adca abea'.match(/a..a/g))
// console.log('aa aba abba abbba abca abea'.match(/a(b+)a/g))
// console.log( 'aa aba abba abbba abca abea'.match(/ab*a/g))
// console.log('aa aba abba abbba abca abea'.match(/ab?a/g))
// console.log('aa aba abba abbba abca abea'.match(/(ab)+/g))
// console.log('a.a aba aea'.match(/a\.a/g))
// console.log('2+3 223 2223'.match(/2\+3/g))
// console.log( '23 2+3 2++3 2+++3 345 567'.match(/2(\+)+3/g))
// console.log( '23 2+3 2++3 2+++3 345 567'.match(/2(\+)*3/g))
// console.log( '*+ *q+ *qq+ *qqq+ *qqq qqq+'.match(/\*q+\+/g))
// console.log('aba accca azzza wwwwa'.replace(/a(?<word>\w+)a/g, '!$<word>!'))
// console.log('aba accca azzza wwwwa'.replace(/^a.+?a$/, '!'))
// console.log('aa aba abba abbba abbbba abbbbba'.match(/ab{2,4}a/g))
// console.log('aa aba abba abbba abbbba abbbbba'.match(/ab{1,3}a/g))
// console.log('aa aba abba abbba abbbba abbbbba'.match(/ab{4,}a/g))
// console.log('a1a a2a a3a a4a a5a aba aca'.match(/a\da/g))
// console.log( 'a1a a22a a333a a4444a a55555a aba aca'.match(/a\d+a/g))
// console.log( 'avb a1b a2b a3b a4b a5b abb acb'.match(/a\D+b/g))
// console.log('ave a#b a2b a$b a4b a5b a-b acb'.match(/a\Wb/g))
// console.log('ave a#a a2a a$a a4a a5a a-a aca'.replace(/\s/g, '!'))
// console.log('aba aea aca aza axa'.match(/a[bex]a/g))
// console.log('aba aea aca aza axa a.a a+a a*a'.match(/a[b.+*]a/g))
// console.log('a1a a2a a3a a4a a5a a6a a7a aba'.match(/a[3-7]a/g))
// console.log('aaa aba aca ada ana a6a aga '.match(/a[a-g]a/g))
// console.log('aaa aBa aca aDa afa aZa aga '.match(/a[a-fA-Z]a/g))
// console.log('aba aea aca aza axa a-a a#a'.match(/a[^ex]a/g))
// console.log('wйw wяw wёw wqw'.match(/w[А-Яа-яЁё]w/gi))
// console.log('aAXa aeffa aGha aza ax23a a3sSa'.match(/a[a-z]+a/g))
// console.log('aAXa aeffa aGha aza ax23a a3sSa'.match(/a[a-zA-Z]+a/g))
// console.log('aAXa aeffa aGha aza ax23a a3sSa'.match(/a[a-z0-9]+a/g))
// console.log('ааа ббб ёёё ззз ййй ААА БББ ЁЁЁ ЗЗЗ ЙЙЙ'.match(/[а-яА-Я]+/gi))
// console.log('aaa aaa aaa'.replace(/^aaa/ig, '!'))
// console.log('aaa aaa aaa'.replace(/aaa$/ig, '!'))
// console.log('aeeea aeea aea axa axxa axxxa'.match(/a(e+|x+)a/g))
// console.log('aeeea aeea aea axa axxa axxxa'.match(/a(e{2}|x+)a/gi))
// console.log( 'a\a abc'.replace(/aa/g, '!'))
// console.log('a\a a\\a a\\\a'.replace(/a(\\\\){3}a/g, '!'))
// console.log('aaa@bbb eee7@kkk'.replace(/(?<one>\w+)@(?<two>\w+)/g, '$<two>@$<one>'))
// console.log('a1b2c3'.replace(/(\d)/g, '$1$1'))
// console.log('mymail@mail.ru my.mail@mail.ru my-mail@mail.ru my_mail@mail.ru mail@mail.com mail@mail.by mail@yandex.ru'.match(/[\w\.-]+@\w+\.\w+/g))
// console.log(/^[a-zA-z]+\W?[a-z]+@[a-zA-z]+\.[a-z]{2,3}$/.test('mymail@mail.ru'))
// console.log(/^[a-zA-z]+\W?[a-z]+@[a-zA-z]+\.[a-z]{2,3}$/.test('my.mail@mail.ru'))
// console.log(/^[a-zA-z]+\W?[a-z]+@[a-zA-z]+\.[a-z]{2,3}$/.test('my-mail@mail.ru'))
// console.log(/^[a-zA-z]+\W?[a-z]+@[a-zA-z]+\.[a-z]{2,3}$/.test('my_mail@mail.ru'))
// console.log('site.ru, site.com, my-site.com'.match(/([a-z]\w+-)?[a-z]\w+\.[a-z]{2,3}/g))
// console.log(/http:\/\/[a-z]+\.[a-z]{2-3}/g.test('http://site.ru'))
// console.log(/http:\/\/[a-z]+\.[a-z]{2-3}/g.test('http://site.com'))
// console.log(/https?:\/\/[a-z]+\.ru/g.test('http://site.ru'))
// console.log(/https?:\/\/[a-z]+\.ru/g.test('https://site.ru'))
// console.log(/\.(txt|html|php)$/g.test('file.txt'))
// console.log(/\.(txt|html|php)$/g.test('file.html'))
// console.log(/\.(txt|html|php)$/g.test('file.php'))
// console.log(/^\d{0,12}$/.test('1111111111')) //<a href="http://site.ru">site.ru</a>
// console.log('http://site.ru, http://site.com'.match(/http:\/\/[a-z]+\.[a-z]{2,3}/g))
// console.log('http://site.ru, http://site.com'.replace(/(?<protocol>http:\/\/)(?<domen>[a-z]+\.[a-z]{2,3})/g, '<a href="$<protocol>$<domen>">$<domen></a>'))
// console.log('1 2  3   4    5     .'.replace(/\s+/g, ' '))
// console.log('aaab'.replace(/aaa(?=b)/g, '!'))
// console.log('aaaw aaab aaal aaab aaat'.replace(/aaa(?!b)/g, '!'))
// console.log('2 4 5 6 10'.replace(/\d+/g, number => number * number))
// console.log("2aaa'3'bbb'4'".replace(/(?<=')\d+(?=')/g, number => number * 2))
// console.log('{{text}} {{hello}} {{12345}}'.replace(/(?<={{)\w+(?=}})/g, str => str.split('').reverse().join('')))
console.log('23 + 35 ='.replace(/(\d+)\s\+\s(\d+)\s=/g, (match, oneNumber, twoNumber) => {
    return match + ' ' + (parseInt(oneNumber) + parseInt(twoNumber))
}))
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()